<?php

$_helper    = $this->helper('catalog/output');
$_category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$_categories = $_category->getCollection()
                          ->addAttributeToSelect(array('name', 'image'))
                          ->addAttributeToFilter('is_active', 1)
                          ->addIdFilter($_category->getChildren())

?>
<div class="products-grid">
	<div class="container-fluid">
		<div class="row">
			<?php foreach ($_categories as $_category): ?>
			<div class="col-md-3 col-sm-6 col-xs-12">
			  <div class="panel panel-default">
				<div class="panel-heading">
				  <a href="<?php echo $_category->getUrl() ?>"><img src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $_category->getImage() ?>" style="height:180px" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /></a>
				</div>
				<div class="panel-body">
				  <h2 class="product-title"><a href="<?php echo $_category->getUrl() ?>" title="<?php echo $this->stripTags($_category->getName(), null, true) ?>"><?php echo $_category->getName() ?></a></h2>
				  <ul class="wish-list">
					  <?php if ($this->helper('wishlist')->isAllow()) : ?>
						  <li><a href="<?php echo $this->getUrl('wishlist') ?>" class="link-wishlist"><img src="<?php echo $this->getSkinUrl('images/favorite.png');?>" title="<?php echo $this->__('Add to Wishlist') ?>" alt"<?php echo $this->__('Add to Wishlist') ?>"></a></li>
					  <?php endif; ?>
					  <?php if($_compareUrl=$this->getAddToCompareUrl($_category)): ?>
						  <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><img src="<?php echo $this->getSkinUrl('images/compare.png');?>" title="<?php echo $this->__('Add to Compare') ?>" alt="<?php echo $this->__('Add to Compare') ?>"></a></li>
					  <?php endif; ?>
				  </ul>
				</div>
			  </div>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
</div>
