<?php
/**
 * Magento
 * @copyright   Copyright ( c ) 2013 www.magebuzz.com
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>

</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col3-layout">
			<div class="main-content">
				<div class="main container">
					<div class="row">
						<?php echo $this->getChildHtml('breadcrumbs') ?>
							<div class="row">
								<div class="col-wrapper col-md-9">
									<div class="row">
										<div class="col-main col-md-8">
											<div class="col-main-content">
												<?php echo $this->getChildHtml('global_messages') ?>
												<?php echo $this->getChildHtml('content') ?>
											</div>
										</div>
										<div class="col-left sidebar col-md-4">
											<div class="sidebar-content">
												<?php echo $this->getChildHtml('left') ?>
											</div>
										</div>
									</div>
								</div>
								<div class="col-right sidebar col-md-3">
									<div class="sidebar-content">
										<?php echo $this->getChildHtml('right') ?>
									</div>
								</div>
							</div>
					</div>
				</div>
			</div>
        </div>
		
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
