<?php 
	$_helper = Mage::helper('banners');
?>	
<?php if(Mage::helper('banners')->isEnableBanners()): ?>
	<?php if(Mage::helper('banners')->includeJqueryLib()): ?>
		<script src="<?php echo $this->getJsUrl('magebuzz/banners/jquery.min.js')?>" type="text/javascript"></script>
		<script src="<?php echo $this->getJsUrl('magebuzz/banners/jquery.noconflict.js')?>" type="text/javascript"></script>
	<?php endif;?>
	<script src="<?php echo $this->getSkinUrl('js/magebuzz/banners/jquery.bxslider.js')?>" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/banners/styles.css')?>" media="all" />
<?php endif;?>