<div id="projects-grid">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-2 col-xs-6 col-sm-4">
        <a class="expander tipped" href="aztecas" data-title="Aztecas" data-tipper-options='{"direction":"top","follow":"true"}'>
          <div class="portfolio-box-1 branding">
            <div class="mask"></div>
            <h3><span>Artesanias</span><br />Aztecas</h3>
            <img src="{{media url="wysiwyg/asteca-grid.jpg"}}" />
          </div>
        </a>
      </div>
      <div class="col-xs-6 col-sm-4">
        <a class="expander tipped" href="mayas" data-title="Mayas" data-tipper-options='{"direction":"top","follow":"true"}'>
          <div class="portfolio-box-1 branding">
            <div class="mask"></div>
            <h3><span>Artesanias</span><br />Mayas</h3>
            <img src="{{media url="wysiwyg/maya-grid.jpg"}}" /></a>
          </div>
        </a>
      </div>
    </div>
    <p>&nbsp;</p>
    <div class="row">
      <div class="col-sm-offset-2 col-xs-6 col-sm-4">
        <a class="expander tipped" href="toltecas" data-title="Toltecas" data-tipper-options='{"direction":"top","follow":"true"}'>
          <div class="portfolio-box-1 branding">
            <div class="mask"></div>
            <h3><span>Artesanias</span><br />Toltecas</h3>
            <img src="{{media url="wysiwyg/tolteca-grid.jpg"}}" />
          </div>
        </a>
      </div>
      <div class="col-xs-6 col-sm-4">
        <a class="expander tipped" href="quechuas" data-title="Quechuas" data-tipper-options='{"direction":"top","follow":"true"}'>
          <div class="portfolio-box-1 branding">
            <div class="mask"></div>
            <h3><span>Artesanias</span><br />Quechuas</h3>
            <img src="{{media url="wysiwyg/quechua-grid.jpg"}}" /></a>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="row">
<div class="col-sm-offset-2 col-xs-6 col-sm-4">
<a href="toltecas" title="Toltecas"><img src="{{media url="wysiwyg/tolteca-grid.jpg"}}" /></a>
<h3 class="text-center"><span>Artesanias</span><br />Toltecas</h3>
</div>
<div class="col-xs-6 col-sm-4"><a href="quechuas" title="Quechuas"></a>
<a href="quechuas" title="Quechuas"><img src="{{media url="wysiwyg/quechua-grid.jpg"}}" /></a>
<h3 class="text-center"><span>Artesanias</span><br />Quechuas</h3>
</div>
</div>
</div>

<div id="projects-grid">
	<a class="expander tipped" href="project1.html" data-title="ajax expander" data-tipper-options='{"direction":"top","follow":"true"}'>
		<div class="portfolio-box-1 branding">
			<div class="mask"></div>
			<h3><span>branding</span><br>project name</h3>
			<img src="images/portfolio/1.jpg" alt="">
		</div>
	</a>
	<a class="expander tipped" href="project2.html" data-title="ajax expander" data-tipper-options='{"direction":"top","follow":"true"}'>
		<div class="portfolio-box-1 photo">
			<div class="mask"></div>
			<h3><span>photo</span><br>project name</h3>
			<img src="images/portfolio/2.jpg" alt="">
		</div>
	</a>
	<a class="expander tipped" href="project3.html" data-title="ajax expander" data-tipper-options='{"direction":"top","follow":"true"}'>
		<div class="portfolio-box-1 motion">
			<div class="mask"></div>
			<h3><span>motion</span><br>project name</h3>
			<img src="images/portfolio/3.jpg" alt="">
		</div>
	</a>
	<a class="expander tipped" href="project4.html" data-title="ajax expander" data-tipper-options='{"direction":"top","follow":"true"}'>
		<div class="portfolio-box-1 branding">
			<div class="mask"></div>
			<h3><span>branding</span><br>project name</h3>
			<img src="images/portfolio/4.jpg" alt="">
		</div>
	</a>
</div>